### ISSUE TITLE
Import ECDSA keys

### ISSUE THREAD

**Issue by udhos** [gitzhou/bitcoin-ecies#1]
Hi,

I am doing some testing among ECIES implementations and trying to use golang ECDSA keys as a common format for all of them.

This is the code I am currently using for github.com/gitzhou/bitcoin-ecies:

```
func encryptBitcoin(pubKey *ecdsa.PublicKey, data []byte) ([]byte, error) {
	pubKeyBytes := append(pubKey.X.Bytes(), pubKey.Y.Bytes()...)
	dataStr, err := bitcoin.EncryptMessage(string(data), pubKeyBytes)
	return []byte(dataStr), err
}

func decryptBitcoin(privKey *ecdsa.PrivateKey, data []byte) ([]byte, error) {
	privKeyBytes := privKey.D.Bytes()
	dataStr, err := bitcoin.DecryptMessage(string(data), privKeyBytes)
	return []byte(dataStr), err
}
```

However it is clearly wrong because it reports this failure for encryption:

`main_test.go:68: key=key1 text=text1 src= bitcoin dst=ethereum error encrypt: invalid pub key length 64`

Can you please help me to understand how to properly import ECDSA keys into the format expected by bitcoin-ecies?

If you want, you can see the full test code:

https://github.com/udhos/ecies-go-test/blob/master/main_test.go

Thanks,
Everton

**Comment by gitzhou** [comment]
Hi, the bitcoin uncompressed public key is 65 byte length, you should add `0x04` before the x coordinate and y coordinate. Check the result of `publicKey, errKey := publicKeyFromPemStr(k.strPEMPub)` in [your code](https://github.com/udhos/ecies-go-test/blob/master/main_test.go#L103).

View the [test code](https://github.com/gitzhou/bitcoin-ecies/blob/master/core_test.go#L49) for more information.  😄

**Comment by udhos** [comment]
Hi!

Thank you for the directions!

I prepended 0x04 and it actually worked. Now the test at least completes without crashing!

I still need to find out why encryption/decryption does not work among distinct implementations.

It seems like each work interoperates only with itself. This is what I am seeing:

```
go test | grep good
    main_test.go:96: key=key1(secp256r1) text=text1 src= ethereum dst= ethereum good
    main_test.go:96: key=key1(secp256r1) text=text1 src= ethereum dst= obscuren good
    main_test.go:96: key=key1(secp256r1) text=text1 src=    havir dst=    havir good
    main_test.go:96: key=key1(secp256r1) text=text1 src= obscuren dst= ethereum good
    main_test.go:96: key=key1(secp256r1) text=text1 src= obscuren dst= obscuren good
    main_test.go:96: key=key2(secp256k1) text=text1 src=  bitcoin dst=  bitcoin good
    main_test.go:96: key=key2(secp256k1) text=text1 src=sghcrypto dst=sghcrypto good
    main_test.go:96: key=key2(secp256k1) text=text1 src= ecies_go dst= ecies_go good
    main_test.go:96: key=key2(secp256k1) text=text1 src=    btcec dst=    btcec good
```

Is this expected? I mean, ECIES does not work across distinct implementations?

Thanks a lot,
Everton

**Comment by gitzhou** [comment]
Probably yes, since different implementations might use different [magic bytes](https://github.com/gitzhou/bitcoin-ecies/blob/master/core.go#L96) or different elliptic curves, not sure, better to read their source code to find out why.
